from collections.abc import Sequence
from typing import Optional, Union

Grid = Sequence[Sequence[float]]
GasPathMode = Union[str, bool]

__version__: str

class ItuError(Exception): ...

class HydrometeorType:
    name: str
    def __init__(self, value: str) -> None: ...
    @staticmethod
    def water() -> HydrometeorType: ...
    @staticmethod
    def ice() -> HydrometeorType: ...

class SlantPathOptions:
    hs_km: Optional[float]
    rho_gm3: Optional[float]
    r001_mmh: Optional[float]
    eta: float
    t: Optional[float]
    h_percent: Optional[float]
    pressure_hpa: Optional[float]
    h_l_m: float
    l_s_km: Optional[float]
    tau_deg: float
    v_t_kgm2: Optional[float]
    exact: bool
    include_rain: bool
    include_gas: bool
    include_scintillation: bool
    include_clouds: bool
    def __init__(
        self,
        hs_km: Optional[float] = None,
        rho_gm3: Optional[float] = None,
        r001_mmh: Optional[float] = None,
        eta: float = 0.5,
        t: Optional[float] = None,
        h_percent: Optional[float] = None,
        pressure_hpa: Optional[float] = None,
        h_l_m: float = 1000.0,
        l_s_km: Optional[float] = None,
        tau_deg: float = 45.0,
        v_t_kgm2: Optional[float] = None,
        exact: bool = False,
        include_rain: bool = True,
        include_gas: bool = True,
        include_scintillation: bool = True,
        include_clouds: bool = True,
    ) -> None: ...
    @staticmethod
    def default() -> SlantPathOptions: ...

class SlantPathContributions:
    gas_db: float
    cloud_db: float
    rain_db: float
    scintillation_db: float
    total_db: float

def topographic_altitude_km(lat_deg: float, lon_deg: float) -> float: ...
def surface_mean_temperature_k(lat_deg: float, lon_deg: float) -> float: ...
def surface_month_mean_temperature_k(lat_deg: float, lon_deg: float, month: int) -> float: ...
def standard_temperature_k(h_km: float) -> float: ...
def standard_pressure_hpa(h_km: float) -> float: ...
def standard_water_vapour_density_gm3(h_km: float, rho0_gm3: float) -> float: ...
def surface_water_vapour_density_gm3(lat_deg: float, lon_deg: float, p: float, alt_km: float) -> float: ...
def total_water_vapour_content_kgm2(lat_deg: float, lon_deg: float, p: float, alt_km: float) -> float: ...
def rainfall_rate_r001_mmh(lat_deg: float, lon_deg: float) -> float: ...
def rainfall_probability_percent(lat_deg: float, lon_deg: float) -> float: ...
def rainfall_rate_mmh(lat_deg: float, lon_deg: float, p: float) -> float: ...
def unavailability_from_rainfall_rate_percent(lat_deg: float, lon_deg: float, rainfall_rate_mmh: float) -> float: ...
def zero_isotherm_height_km(lat_deg: float, lon_deg: float) -> float: ...
def rain_height_km(lat_deg: float, lon_deg: float) -> float: ...
def rain_specific_attenuation_coefficients(freq_ghz: float, elevation_deg: float, tau_deg: float) -> tuple[float, float]: ...
def rain_specific_attenuation_db_per_km(rainfall_rate_mmh: float, freq_ghz: float, elevation_deg: float, tau_deg: float) -> float: ...
def cloud_reduced_liquid_kgm2(lat_deg: float, lon_deg: float, p: float) -> float: ...
def cloud_liquid_mass_absorption_coefficient(freq_ghz: float) -> float: ...
def cloud_specific_attenuation_coefficient(freq_ghz: float, temp_c: float) -> float: ...
def cloud_attenuation_db(lat_deg: float, lon_deg: float, elevation_deg: float, freq_ghz: float, p: float, lred_kgm2: Optional[float] = None) -> float: ...
def lognormal_approximation_coefficients(lat_deg: float, lon_deg: float) -> tuple[float, float, float]: ...
def cloud_attenuation_lognormal_db(lat_deg: float, lon_deg: float, elevation_deg: float, freq_ghz: float, p: float) -> float: ...
def wet_term_radio_refractivity(e_hpa: float, temp_c: float) -> float: ...
def dry_term_radio_refractivity(pd_hpa: float, temp_k: float) -> float: ...
def radio_refractive_index(pd_hpa: float, e_hpa: float, temp_k: float) -> float: ...
def water_vapour_pressure_hpa(temp_c: float, pressure_hpa: float, humidity_percent: float) -> float: ...
def saturation_vapour_pressure_hpa(temp_c: float, pressure_hpa: float, hydrometeor: Union[HydrometeorType, str]) -> float: ...
def map_wet_term_radio_refractivity(lat_deg: float, lon_deg: float, p: float) -> float: ...
def dn65(lat_deg: float, lon_deg: float, p: float) -> float: ...
def dn1(lat_deg: float, lon_deg: float, p: float) -> float: ...
def inter_annual_variability(p_fraction: float, lat_deg: float, lon_deg: float) -> float: ...
def risk_of_exceedance(p_fraction: float, pr_fraction: float, lat_deg: float, lon_deg: float) -> float: ...
def is_regular_grid(lat_grid: Grid, lon_grid: Grid) -> bool: ...
def nearest_2d_interpolate(lat_grid: Grid, lon_grid: Grid, values: Grid, lat_deg: float, lon_deg: float) -> float: ...
def bilinear_2d_interpolate(lat_grid: Grid, lon_grid: Grid, values: Grid, lat_deg: float, lon_deg: float) -> float: ...
def bicubic_2d_interpolate(lat_grid: Grid, lon_grid: Grid, values: Grid, lat_deg: float, lon_deg: float) -> float: ...
def gamma0_exact_db_per_km(freq_ghz: float, pressure_hpa: float, rho_gm3: float, temp_k: float) -> float: ...
def gammaw_exact_db_per_km(freq_ghz: float, pressure_hpa: float, rho_gm3: float, temp_k: float) -> float: ...
def gamma_exact_db_per_km(freq_ghz: float, pressure_hpa: float, rho_gm3: float, temp_k: float) -> float: ...
def gamma0_approx_db_per_km(freq_ghz: float, pressure_hpa: float, rho_gm3: float, temp_k: float) -> float: ...
def gammaw_approx_db_per_km(freq_ghz: float, pressure_hpa: float, rho_gm3: float, temp_k: float) -> float: ...
def slant_inclined_path_equivalent_height_km(freq_ghz: float, pressure_hpa: float, rho_gm3: float, temp_k: float) -> tuple[float, float]: ...
def zenith_water_vapour_attenuation_db(freq_ghz: float, v_t_kgm2: float, h_km: float) -> float: ...
def gaseous_attenuation_slant_path_db(freq_ghz: float, elevation_deg: float, rho_gm3: float, pressure_hpa: float, temp_k: float, v_t_kgm2: float, h_km: float, exact: bool) -> float: ...
def gaseous_attenuation_terrestrial_path_db(path_length_km: float, freq_ghz: float, elevation_deg: float, rho_gm3: float, pressure_hpa: float, temp_k: float, mode: GasPathMode) -> float: ...
def gaseous_attenuation_inclined_path_db(freq_ghz: float, elevation_deg: float, rho_gm3: float, pressure_hpa: float, temp_k: float, h1_km: float, h2_km: float, mode: GasPathMode) -> float: ...
def rain_attenuation_db(lat_deg: float, lon_deg: float, freq_ghz: float, elevation_deg: float, hs_km: float, p: float, r001_mmh: Optional[float], tau_deg: float, l_s_km: Optional[float]) -> float: ...
def rain_attenuation_probability_percent(lat_deg: float, lon_deg: float, elevation_deg: float, hs_km: Optional[float], l_s_km: Optional[float], p0_percent: Optional[float]) -> float: ...
def fit_rain_attenuation_to_lognormal(lat_deg: float, lon_deg: float, freq_ghz: float, elevation_deg: float, hs_km: float, p_k_percent: float, tau_deg: float) -> tuple[float, float]: ...
def site_diversity_rain_outage_probability_percent(lat1_deg: float, lon1_deg: float, a1_db: float, elevation1_deg: float, lat2_deg: float, lon2_deg: float, a2_db: float, elevation2_deg: float, freq_ghz: float, tau_deg: float, hs1_km: Optional[float], hs2_km: Optional[float]) -> float: ...
def rain_cross_polarization_discrimination_db(attenuation_db: float, freq_ghz: float, elevation_deg: float, p: float, tau_deg: float) -> float: ...
def scintillation_sigma_db(lat_deg: float, lon_deg: float, freq_ghz: float, elevation_deg: float, dish_m: float, eta: float, temp_c: Optional[float], humidity_percent: Optional[float], pressure_hpa: Optional[float], h_l_m: float) -> float: ...
def scintillation_attenuation_db(lat_deg: float, lon_deg: float, freq_ghz: float, elevation_deg: float, p: float, dish_m: float, eta: float, temp_c: Optional[float], humidity_percent: Optional[float], pressure_hpa: Optional[float], h_l_m: float) -> float: ...
def gas_attenuation_default(lat_deg: float, lon_deg: float, freq_ghz: float, elevation_deg: float, p: float, d_m: float) -> float: ...
def gas_attenuation_default_many(lat_deg: float, lon_deg: float, freq_ghz: float, elevation_deg: Sequence[float], p: float, d_m: float) -> list[float]: ...
def gas_attenuation_default_many_checked(lat_deg: float, lon_deg: float, freq_ghz: float, elevation_deg: Sequence[float], p: float, d_m: float) -> list[float]: ...
def atmospheric_attenuation_slant_path(lat_deg: float, lon_deg: float, freq_ghz: float, elevation_deg: float, p: float, d_m: float, options: Optional[SlantPathOptions] = None) -> SlantPathContributions: ...
def atmospheric_attenuation_slant_path_many(lat_deg: float, lon_deg: float, freq_ghz: float, elevation_deg: Sequence[float], p: float, d_m: float, options: Optional[SlantPathOptions] = None) -> list[SlantPathContributions]: ...
